#!/usr/bin/env node
// generate-credits.mjs — emit CREDITS/AUDIO-CREDITS.txt and .csv from the
// registry (plan s38). CC0 assets stay listed for provenance.
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { CREDITS_DIR, loadRegistry, outputStem, resolveProcessedExt, eventNumbering } from "./lib/common.mjs";

function main() {
  const reg = loadRegistry();
  const numbering = eventNumbering(reg);
  const lines = [
    "AUDIO CREDITS",
    "=============",
    "",
    "Generated by tools/audio-pipeline/scripts/generate-credits.mjs —",
    "edit metadata/licenses.json, then run `npm run audio:credits`.",
    "",
  ];
  const csv = ["asset,event,file,original_title,creator,site,url,license,license_url,date"];

  for (const asset of reg.assets) {
    const src = asset.source ?? {};
    const lic = asset.license ?? {};
    lines.push(`${asset.id}`, "-".repeat(asset.id.length));
    lines.push(`Title:     ${src.title ?? "?"}`);
    lines.push(`Author:    ${src.creator ?? "?"}`);
    lines.push(`Website:   ${src.site ?? "?"}`);
    lines.push(`Source:    ${src.url ?? "(project-original)"}`);
    if (src.downloadDate) lines.push(`Obtained:  ${src.downloadDate}`);
    lines.push(
      `License:   ${lic.name ?? "?"}${lic.url ? ` (${lic.url})` : ""} — attribution ${
        lic.attributionRequired ? "REQUIRED" : "not required"
      }`
    );
    const status = asset.review?.status ?? "?";
    lines.push(`Status:    ${status}${status === "approved" ? "" : " (NOT in production soundtrack)"}`);

    for (const [eventId, mappings] of Object.entries(asset.events ?? {})) {
      for (let i = 0; i < mappings.length; i++) {
        const seq = numbering.get(`${asset.id}|${eventId}|${i}`);
        const stem = outputStem(eventId, seq);
        const ext = resolveProcessedExt(asset.id, stem) ?? ".ogg";
        csv.push(
          [
            asset.id, eventId, `${asset.id}/${stem}${ext}`,
            src.title ?? "", src.creator ?? "", src.site ?? "", src.url ?? "",
            lic.name ?? "", lic.url ?? "", src.downloadDate ?? "",
          ]
            .map((v) => `"${String(v).replace(/"/g, '""')}"`)
            .join(",")
        );
      }
    }
    lines.push("");
  }

  mkdirSync(CREDITS_DIR(), { recursive: true });
  writeFileSync(CREDITS_DIR("AUDIO-CREDITS.txt"), lines.join("\n") + "\n");
  writeFileSync(CREDITS_DIR("AUDIO-CREDITS.csv"), csv.join("\n") + "\n");
  console.log(`credits: ${reg.assets.length} assets -> ${path.join("CREDITS", "AUDIO-CREDITS.txt")} + .csv`);
}

main();
