// generate-credits.mjs — Aggregate attribution for all LPC definitions into
// project-level credit files consumed by NOTICE/CONTRIBUTING workflows:
//   CREDITS/LPC-CREDITS.txt   human-readable, grouped by license
//   CREDITS/LPC-CREDITS.csv   machine-readable per-asset rows
// Sources of truth: tools/lpc-factory/definitions/{characters,weapons,generated}/
// Usage:
//   node scripts/generate-credits.mjs [--check] [--out-dir DIR]
// --check regenerates in memory and exits 1 if the on-disk files differ.

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

import { loadDefinition, loadDefinitionsFromDir,
  normalizeCharacterDef, normalizeWeaponDef, weaponToCharacterDef } from "./lib/definitions.mjs";
import { collectCredits, getUniqueAuthors } from "./lib/credits.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const FACTORY_ROOT = path.resolve(__dirname, "..");
const REPO_ROOT = path.resolve(FACTORY_ROOT, "..", "..");
const DEFAULT_OUT_DIR = path.join(REPO_ROOT, "CREDITS");

function collectDefinitionFiles() {
  const dirs = ["characters", "weapons", "generated"]
    .map(d => path.join(FACTORY_ROOT, "definitions", d))
    .filter(d => fs.existsSync(d));
  const files = [];
  for (const dir of dirs) {
    for (const entry of fs.readdirSync(dir)) {
      if (/\.(ya?ml|json)$/i.test(entry) && !entry.startsWith(".")) {
        files.push(path.join(dir, entry));
      }
    }
  }
  return files.sort();
}

function aggregateCredits(assetIndex) {
  const byKey = new Map(); // item:file -> credit row
  const sourcesByItem = new Map(); // item -> Set(character names)
  let defCount = 0;
  let skippedDefs = [];

  for (const file of collectDefinitionFiles()) {
    let raw;
    try {
      raw = loadDefinition(file);
    } catch (e) {
      skippedDefs.push(path.basename(file) + ": " + e.message);
      continue;
    }
    const isWeapon = raw.item !== undefined && raw.layers === undefined;
    const def = isWeapon
      ? weaponToCharacterDef(normalizeWeaponDef(raw))
      : normalizeCharacterDef(raw);

    // Drop layers referencing unknown catalog items so one bad definition
    // doesn't poison the whole aggregation; record for reporting.
    const knownLayers = [];
    for (const layer of def.layers) {
      if (!assetIndex.catalog[layer.item]) continue;
      knownLayers.push(layer);
      if (!sourcesByItem.has(layer.item)) sourcesByItem.set(layer.item, new Set());
      sourcesByItem.get(layer.item).add(def.name);
    }
    if (knownLayers.length === 0) continue;

    defCount++;
    const credits = collectCredits({ ...def, layers: knownLayers }, assetIndex);
    for (const c of credits) {
      const key = c.item + ":" + c.file;
      if (!byKey.has(key)) byKey.set(key, c);
    }
  }

  const credits = [...byKey.values()].sort((a, b) =>
    a.item === b.item ? a.file.localeCompare(b.file) : a.item.localeCompare(b.item));
  return { credits, defCount, skippedDefs, sourcesByItem };
}

function formatTxt(credits, authors, sourcesByItem) {
  const licenses = [...new Set(credits.flatMap(c => c.licenses))].sort();
  let out = "";
  out += "# LPC sprite attributions\n\n";
  out += "Generated by tools/lpc-factory/scripts/generate-credits.mjs.\n";
  out += "Do not edit by hand — rerun the generator after definition changes.\n\n";
  out += "## Licenses used\n\n";
  for (const lic of licenses) out += "- " + lic + "\n";
  out += "\n## Authors\n\n";
  for (const a of authors) {
    out += "- " + a.name + " (" + a.licenses.join(", ") + ")";
    if (a.urls.length > 0) out += " — " + a.urls.join(", ");
    out += "\n";
  }
  out += "\n## Assets (" + credits.length + ")\n\n";
  for (const c of credits) {
    out += "### " + c.itemName + " (`" + c.item + "`)\n\n";
    out += "- File(s): `" + c.file + "`\n";
    out += "- Used by: " + [...(sourcesByItem.get(c.item) || [])].sort().join(", ") + "\n";
    out += "- Authors: " + c.authors.join(", ") + "\n";
    out += "- Licenses: " + c.licenses.join(", ") + "\n";
    if (c.urls.length > 0) out += "- URLs: " + c.urls.join(" ") + "\n";
    if (c.notes) out += "- Notes: " + c.notes + "\n";
    out += "\n";
  }
  return out;
}

function csvEscape(v) {
  const s = String(v == null ? "" : v);
  return /[",\n]/.test(s) ? "\"" + s.replace(/"/g, "\"\"") + "\"" : s;
}

function formatCsv(credits) {
  const header = "item,item_name,file,authors,licenses,urls,notes";
  const rows = credits.map(c => [
    c.item, c.itemName, c.file,
    c.authors.join("; "), c.licenses.join("; "),
    c.urls.join(" "), c.notes,
  ].map(csvEscape).join(","));
  return [header, ...rows].join("\n") + "\n";
}

function parseArgs(argv) {
  const args = argv.slice(2);
  const options = {};
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--check") options.check = true;
    else if (args[i] === "--out-dir" || args[i] === "-o") options.outDir = args[++i];
    else if (args[i] === "--help" || args[i] === "-h") {
      console.log("Usage: node scripts/generate-credits.mjs [--check] [--out-dir DIR]");
      process.exit(0);
    }
  }
  return options;
}

const options = parseArgs(process.argv);
const assetIndex = JSON.parse(fs.readFileSync(
  path.join(FACTORY_ROOT, "metadata", "asset-index.json"), "utf8"));

const { credits, defCount, skippedDefs, sourcesByItem } = aggregateCredits(assetIndex);
if (skippedDefs.length > 0) {
  console.warn("Skipped unparseable definitions:");
  skippedDefs.forEach(s => console.warn("  - " + s));
}
console.log("Aggregated " + credits.length + " unique asset credits from " +
  defCount + " definition(s)");

const authors = getUniqueAuthors(credits);
const txt = formatTxt(credits, authors, sourcesByItem);
const csv = formatCsv(credits);
const outDir = options.outDir || DEFAULT_OUT_DIR;
const txtPath = path.join(outDir, "LPC-CREDITS.txt");
const csvPath = path.join(outDir, "LPC-CREDITS.csv");

if (options.check) {
  const currentTxt = fs.existsSync(txtPath) ? fs.readFileSync(txtPath, "utf8") : "";
  const currentCsv = fs.existsSync(csvPath) ? fs.readFileSync(csvPath, "utf8") : "";
  if (currentTxt === txt && currentCsv === csv) {
    console.log("CHECK PASS: credit files are up to date (" + txtPath + ")");
    process.exit(0);
  }
  console.error("CHECK FAIL: credit files are stale or missing:");
  if (currentTxt !== txt) console.error("  - " + txtPath + " differs");
  if (currentCsv !== csv) console.error("  - " + csvPath + " differs");
  process.exit(1);
}

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(txtPath, txt, "utf8");
fs.writeFileSync(csvPath, csv, "utf8");
console.log("Wrote " + txtPath);
console.log("Wrote " + csvPath);
